### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by Alexander-Wilms** [LibrePCB/librepcb-rfcs#26]
I'm not sure if this or [LibrePCB/librepcb](https://github.com/LibrePCB/librepcb) is the proper place to file this request. I think it would be nice if LibrePCB could be provided as a [Flatpak](https://flatpak.org/)  via [Flathub](https://flathub.org/). Below is a simple manifest, which I used to build LibrePCB. It seems to work fine so far; you can test it like this:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.kde.Sdk 5.11
flapak-builder --force-clean --ccache --repo=librepcb-repo librepcb-build org.librepcb.LibrePCB.yaml
flatpak remote-add --no-gpg-verify librepcb-repo librepcb-repo
flatpak install librepcb-repo org.librepcb.LibrePCB
flatpak run org.librepcb.LibrePCB
```

Contents of org.librepcb.LibrePCB.yaml:
```
app-id: org.librepcb.LibrePCB
runtime: org.kde.Sdk
runtime-version: 5.11
sdk: org.kde.Sdk
command: librepcb
rename-icon: librepcb
rename-desktop-file: librepcb.desktop
rename-appdata-file: librepcb.appdata.xml
finish-args:
- --socket=wayland
- --socket=x11
- --share=ipc
- --device=dri
- --share=network
- --filesystem=home # required for creating the workspace, downloading libraries etc.
cleanup:
- /include
modules:

- name: librepcb
  buildsystem: qmake
  builddir: true
  sources:
  - type: git
    url: https://github.com/LibrePCB/LibrePCB
  - type: file
    path: librepcb.appdata.xml
  post-install:  
  - install -Dm 644 /app/share/pixmaps/librepcb.svg /app/share/icons/hicolor/scalable/apps/librepcb.svg
  - install -Dm 644 ../librepcb.appdata.xml /app/share/metainfo/librepcb.appdata.xml
```

You also need the appdata file from https://github.com/LibrePCB/LibrePCB/issues/314
